baseURL=https://testing-firesolution.mitroztech.com/Administration/Login
username=admin
password=admin
chromepath=./Drivers\\chromedriver.exe
geckopath=./Drivers\\geckodriver.exe
edgepath=./Drivers\\msedgedriver.exe


CompanyName=vishal building material suppliers

Address=plot no.123, H12 sector2, shivaji park, pune
mobileNumber=9893992307
email=vishal@gmail.com